"""add_price_breakdown_column

Revision ID: 7c112877c2e9
Revises: 9977582da7b2
Create Date: 2026-06-24 00:33:08.218789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c112877c2e9'
down_revision = '9977582da7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_breakdown', sa.Text(), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_breakdown', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('price_breakdown')

    with op.batch_alter_table('booking_enquiries', schema=None) as batch_op:
        batch_op.drop_column('price_breakdown')

    # ### end Alembic commands ###
