"""add indexes for optimization

Revision ID: e259d0ffb219
Revises: fb0c88286bfe
Create Date: 2026-06-29 12:08:24.906135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e259d0ffb219'
down_revision = 'fb0c88286bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_enquiries_check_in_date'), ['check_in_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_enquiries_status'), ['status'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_check_in_date'), ['check_in_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_check_in_date'))

    with op.batch_alter_table('booking_enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_enquiries_status'))
        batch_op.drop_index(batch_op.f('ix_booking_enquiries_check_in_date'))

    # ### end Alembic commands ###
