"""add_missing_fk_columns

Revision ID: fb0c88286bfe
Revises: 7c112877c2e9
Create Date: 2026-06-28 14:15:50.536538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0c88286bfe'
down_revision = '7c112877c2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'accommodations', ['accommodation_id'], ['id'])
        batch_op.create_foreign_key(None, 'accommodation_packages', ['package_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accommodations', ['accommodation_id'], ['id'])
        batch_op.create_foreign_key(None, 'accommodation_packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('package_id')
        batch_op.drop_column('accommodation_id')

    with op.batch_alter_table('booking_enquiries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('total_price')
        batch_op.drop_column('package_id')
        batch_op.drop_column('accommodation_id')

    # ### end Alembic commands ###
